/*
SELECT FLAVOR
FROM (
    SELECT F.FLAVOR, F.TOTAL_ORDER, I.INGREDIENT_TYPE
    FROM FIRST_HALF F
    JOIN ICECREAM_INFO I
    ON F.FLAVOR = I.FLAVOR
) AS IcecreamTable
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based';
*/

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ICECREAM_INFO I
ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC;